version: '3.4'

services:

  loadbalancer:
    image: nginx
    depends_on:
      - signalrbackplaneweb01
      - signalrbackplaneweb02
      - signalrbackplaneweb03

    ports:
      - "5000:80"
    networks:
      - backplane
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  signalrbackplaneweb01:
    container_name: signalrbackplaneweb01
    image: fabricioveronez/signalr-chat-back
    build:
      context: .
      dockerfile: SignalRBackPlane.Web/Dockerfile
    networks:
      - backplane
    depends_on:
      - backplaneredis

  signalrbackplaneweb02:
    container_name: signalrbackplaneweb02
    image: fabricioveronez/signalr-chat-back
    build:
      context: .
      dockerfile: SignalRBackPlane.Web/Dockerfile
    networks:
      - backplane
    depends_on:
      - backplaneredis
  
  signalrbackplaneweb03:
    container_name: signalrbackplaneweb03
    image: fabricioveronez/signalr-chat-back
    build:
      context: .
      dockerfile: SignalRBackPlane.Web/Dockerfile
    networks:
      - backplane
    depends_on:
      - backplaneredis

  backplaneredis:
    container_name: backplaneredis
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    networks:
      - backplane

networks: 
  backplane: 
    driver: bridge